# Generated by Django 4.2.7 on 2024-01-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='amount',
            new_name='balance',
        ),
    ]
