# Generated by Django 4.2.7 on 2024-01-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0004_alter_useraccount_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user',
            new_name='account',
        ),
    ]
