# Generated by Django 4.2.7 on 2024-01-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='book',
        ),
    ]
