# Generated by Django 4.2.7 on 2024-01-23 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAccount', '0004_alter_useraccount_balance'),
        ('transaction', '0002_remove_transactionmodel_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='user_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='UserAccount.useraccount'),
        ),
    ]
