# Generated by Django 4.2.7 on 2024-01-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transactionmodel_user_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='user_account',
            new_name='account',
        ),
    ]
